# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "yeseul.log"
weight = 1

[ko]
languageName = "Korean"
title = "yeseul.log"
weight = 1

[ko.params]
description = ""
