# Change baseurl before deploy
baseurl = "https://HongYeseul.github.io"
languageCode = "ko-KR"
defaultContentLanguage = "ko"
hasCJKLanguage = true

disqusShortname = "hugo-theme-stack"
paginate = 5

title = "예슬"
copyright = "Yeseul Hong"
disqusShortname = "hugo-theme-stack"
enableEmoji = true

enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5
